name: Trivia
author: KingOfMars4
main: me.kingofmars4.trivia.Main
version: 1.0
description: Trivia minigame by KingOfMars4.
depend: [PointsSystem]
commands:
    triviastart:
        usage: /triviastart
    triviarestart:
        usage: /triviarestart