Options:
    pluginPrefix: '&4[Trivia] '
    
Questions: 
    Question1:
        Quest: 'What is the result of 3+1?'
        Answer: '4'
    Question2:
        Quest: 'What is the result of 3+1?'
        Answer: '4'